version: '3.1'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    volumes:
      - ./testdata:/docker-entrypoint-initdb.d:ro
