name: go

on:
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - '**.go'
      - go.*
  push:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - '**.go'
      - go.*

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.3
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          args: --timeout=3m

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.3
      - run: go mod tidy
      - uses: int128/update-generated-files-action@v2

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.3
      - run: docker-compose up -d
      - run: go run .
        env:
          DATABASE_URL: postgresql://app:example@localhost/app
